const sql_pattern = [
  { pattern: /'/g, replacement: "" },
  { pattern: /\\/g, replacement: "" },
  { pattern: /"/g, replacement: "" },
  { pattern: /--/g, replacement: "" },
  { pattern: /;/g, replacement: "" },
  { pattern: /\/\*/g, replacement: "" },
  { pattern: /\*\//g, replacement: "" },
  { pattern: /%00/g, replacement: "" },
  { pattern: /%0/g, replacement: "" },
  { pattern: /%20/g, replacement: " " },
  { pattern: /%27/g, replacement: "'" },
  { pattern: /%22/g, replacement: '"' },
  { pattern: /%09/g, replacement: " " },
  { pattern: /%0A/g, replacement: " " },
  { pattern: /%0D/g, replacement: " " },
  { pattern: /\x00/g, replacement: "" },
  { pattern: /\x1a/g, replacement: "" },
  { pattern: /UNION/gi, replacement: "" },
  { pattern: /SELECT/gi, replacement: "" },
  { pattern: /INSERT/gi, replacement: "" },
  { pattern: /UPDATE/gi, replacement: "" },
  { pattern: /DELETE/gi, replacement: "" },
  { pattern: /DROP/gi, replacement: "" },
  { pattern: /TRUNCATE/gi, replacement: "" },
  { pattern: /OR\s+1=1/gi, replacement: "" },
  { pattern: /OR\s+'1'='1/gi, replacement: "" },
  { pattern: /WAITFOR\s+DELAY/gi, replacement: "" },
  { pattern: /BENCHMARK\(/gi, replacement: "" },
  { pattern: /ALTER/gi, replacement: "" },
  { pattern: /CREATE/gi, replacement: "" },
  { pattern: /EXEC/gi, replacement: "" },
  { pattern: /EXECUTE/gi, replacement: "" },
  { pattern: /INFORMATION_SCHEMA/gi, replacement: "" },
  { pattern: /SYSCOLUMNS/gi, replacement: "" },
  { pattern: /SYSOBJECTS/gi, replacement: "" },
  { pattern: /SLEEP\(/gi, replacement: "" },
  { pattern: /LOAD_FILE/gi, replacement: "" },
  { pattern: /INTO\s+OUTFILE/gi, replacement: "" },
];

const js_pattern = [
  { pattern: /<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/gi, replacement: "" },
  { pattern: /javascript:/gi, replacement: "" },
  { pattern: /onerror/gi, replacement: "" },
  { pattern: /onload/gi, replacement: "" },
  { pattern: /onclick/gi, replacement: "" },
  { pattern: /onmouseover/gi, replacement: "" },
  { pattern: /onmouseout/gi, replacement: "" },
  { pattern: /onkeydown/gi, replacement: "" },
  { pattern: /onkeyup/gi, replacement: "" },
  { pattern: /onkeypress/gi, replacement: "" },
  { pattern: /onsubmit/gi, replacement: "" },
  { pattern: /onchange/gi, replacement: "" },
  { pattern: /onfocus/gi, replacement: "" },
  { pattern: /onblur/gi, replacement: "" },
  { pattern: /eval\(/gi, replacement: "" },
  { pattern: /alert\(/gi, replacement: "" },
  { pattern: /document\.cookie/gi, replacement: "" },
  { pattern: /localStorage/gi, replacement: "" },
  { pattern: /sessionStorage/gi, replacement: "" },
  { pattern: /\(\s*\)\s*=>/g, replacement: "" },
  { pattern: /new\s+Function/gi, replacement: "" },
  { pattern: /setTimeout\(/gi, replacement: "" },
  { pattern: /setInterval\(/gi, replacement: "" },
  { pattern: /%3C/gi, replacement: "" },
  { pattern: /%3E/gi, replacement: "" },
  { pattern: /%22/gi, replacement: "" },
  { pattern: /%27/gi, replacement: "" },
  { pattern: /%60/gi, replacement: "" },
  { pattern: /document\.write/gi, replacement: "" },
  { pattern: /window\.location/gi, replacement: "" },
  { pattern: /\.innerHTML/gi, replacement: "" },
  { pattern: /\.outerHTML/gi, replacement: "" },
  { pattern: /document\.execCommand/gi, replacement: "" },
  { pattern: /Function\(/gi, replacement: "" },
  { pattern: /\.setAttribute\(/gi, replacement: "" },
  { pattern: /document\.domain/gi, replacement: "" },
  { pattern: /\.src\s*=/gi, replacement: "" },
  { pattern: /\.href\s*=/gi, replacement: "" },
  { pattern: /XMLHttpRequest/gi, replacement: "" },
  { pattern: /fetch\(/gi, replacement: "" },
  { pattern: /document\.createElement\(/gi, replacement: "" },
  { pattern: /document\.getElementById\(/gi, replacement: "" },
  { pattern: /document\.getElementsByClassName\(/gi, replacement: "" },
  { pattern: /document\.getElementsByTagName\(/gi, replacement: "" },
  { pattern: /document\.querySelector\(/gi, replacement: "" },
  { pattern: /document\.querySelectorAll\(/gi, replacement: "" },
  { pattern: /\.appendChild\(/gi, replacement: "" },
  { pattern: /\.removeChild\(/gi, replacement: "" },
  { pattern: /\.replaceChild\(/gi, replacement: "" },
  { pattern: /\.insertBefore\(/gi, replacement: "" },
  { pattern: /\.insertAdjacentHTML\(/gi, replacement: "" },
  { pattern: /window\.open\(/gi, replacement: "" },
  { pattern: /\.postMessage\(/gi, replacement: "" },
];

const SANITIZATION_PATTERNS = {
  SQL: sql_pattern,
  JS: js_pattern,
};

export default SANITIZATION_PATTERNS;
